<a href="https://colab.research.google.com/github/Kpaul-create/first/blob/main/Tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow Basics

## Importing TENSORFLOW

### basic functions

In [1]:
import tensorflow as tf

#importing a tensor
X=tf.constant(7)
y=tf.constant(8,shape=(1,1),dtype=tf.float32)
z=tf.constant([[1,2,3],[4,5,6]])
k=tf.random.normal((3,3), mean=0, stddev=1)
j=tf.ones((2,3))
q=tf.range(start=1,limit=10,delta=2)
d=tf.eye(2,3)
p=tf.random.uniform((1,4,2),minval=0,maxval=1)
u=tf.cast(y,dtype=tf.float64)#we can also use tf.float()

print(u)
print(q)
print(p)
print(k)
print(X)
print(y)
print(z)

tf.Tensor([[8.]], shape=(1, 1), dtype=float64)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor(
[[[0.08051014 0.626475  ]
  [0.54755616 0.05322635]
  [0.07542455 0.30198812]
  [0.36096656 0.0263747 ]]], shape=(1, 4, 2), dtype=float32)
tf.Tensor(
[[ 1.2846276   0.36405587  0.59159046]
 [-2.1281984   0.8645758  -1.8236996 ]
 [-1.0900611  -0.85993135  1.2526    ]], shape=(3, 3), dtype=float32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor([[8.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


### Mathematical opertaions

In [7]:
x=tf.constant([1,2,3,4,5])
y=tf.constant([6,7,8,9,10])
print(tf.multiply(x,y))#or x*y
print(tf.add(x,y))
print(tf.subtract(x,y))
print(tf.divide(x,y))

k=tf.tensordot(x,y,axes=1)
print(k)
#or
print(tf.reduce_sum(x*y,axis=0))

print(x**5)
z=tf.random.normal((1,1),mean=5,stddev=10)
print(z)
print(tf.reduce_sum(z,axis=0))
print(tf.reduce_sum(z,axis=1))
#print(tf.matmul(x,y))
#print(x@y)

tf.Tensor([ 6 14 24 36 50], shape=(5,), dtype=int32)
tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)
tf.Tensor([-5 -5 -5 -5 -5], shape=(5,), dtype=int32)
tf.Tensor([0.16666667 0.28571429 0.375      0.44444444 0.5       ], shape=(5,), dtype=float64)
tf.Tensor(130, shape=(), dtype=int32)
tf.Tensor(130, shape=(), dtype=int32)
tf.Tensor([   1   32  243 1024 3125], shape=(5,), dtype=int32)
tf.Tensor([[-1.7270098]], shape=(1, 1), dtype=float32)
tf.Tensor([-1.7270098], shape=(1,), dtype=float32)
tf.Tensor([-1.7270098], shape=(1,), dtype=float32)


### indexing

In [9]:
x=tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])
indices=tf.constant([0,3])
x_ind=tf.gather(x,indices)
print(x_ind)
x=tf.constant([[1,2],
               [3,4],
               [5,6]])
print(x[0,:])
print(x[0:2,:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([0 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### Reshaping

In [13]:
x=tf.constant([0,1,1,2,3,1,2,3])
#x=tf.reshape(x,(3,3))
print(x)
#print(tf.transpose(x,perm=[1,0]))

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
